import { request } from '@/api/core';
import { cookies } from 'next/headers';
import '@/assets/css/global.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  request('/user').then(res => console.log(res));

  return (
    <main className='flex justify-center items-center h-screen'>
      <section className='p-10 w-2/4 border-zinc-500 border-2 rounded'>
        {children}
      </section>
    </main>
  );
}
