import '@/assets/css/global.css';
import Header from '@/components/header';
import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className='dark'>
      {/* <body className={inter.className}> */}
      <body className='pt-header-height'>
        <Header></Header>
        <main className='container pt-3'>{children}</main>
      </body>
    </html>
  );
}
