import '@/assets/css/global.css';
import Header from '@/components/header';
import type { Metadata } from 'next';
import InitComponent from '@/app/init';
import Provider from '@/store/provider';
import { Toaster } from '@/components/ui/toaster';
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className='dark'>
      <body className='pt-header-height'>
        <Provider>
          <Header></Header>
          <main className='container pt-3'>{children}</main>
          <InitComponent />
          <Toaster></Toaster>
        </Provider>
      </body>
    </html>
  );
}

export default RootLayout;